---
- name: Assert usage of systemd as an init system
  assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This role only works with systemd"

- name: Get systemd version
  command: systemctl --version
  changed_when: false
  check_mode: false
  register: __systemd_version
  tags:
    - skip_ansible_lint

- name: Set systemd version fact
  set_fact:
    rpi_exporter_systemd_version: "{{ __systemd_version.stdout_lines[0] | regex_replace('^systemd\\s(\\d+).*$', '\\1') }}"

- name: Naive assertion of proper listen address
  assert:
    that:
      - "':' in rpi_exporter_web_listen_address"

- name: Check if rpi_exporter is installed
  stat:
    path: "/usr/local/bin/rpi_exporter"
  register: __rpi_exporter_is_installed
  tags:
    - rpi_exporter_install

- name: Gather currently installed rpi_exporter version (if any)
  command: "/usr/local/bin/rpi_exporter --version"
  changed_when: false
  register: __rpi_exporter_current_version_output
  when: __rpi_exporter_is_installed.stat.exists
  tags:
    - rpi_exporter_install
    - skip_ansible_lint

- block:
    - name: Get latest release
      uri:
        url: "https://api.github.com/repos/lukasmalkmus/rpi_exporter/releases/latest"
        method: GET
        return_content: true
        status_code: 200
        body_format: json
        validate_certs: false
        user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
        password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
      no_log: "{{ not lookup('env', 'MOLECULE_DEBUG') | bool }}"
      register: _latest_release
      until: _latest_release.status == 200
      retries: 5

    - name: "Set rpi_exporter version to {{ _latest_release.json.tag_name[1:] }}"
      set_fact:
        rpi_exporter_version: "{{ _latest_release.json.tag_name[1:] }}"
  when: rpi_exporter_version == "latest"
  delegate_to: localhost
  run_once: true

- name: Get checksum list from github
  set_fact:
    _checksums: "{{ lookup('url', 'https://github.com/lukasmalkmus/rpi_exporter/releases/download/v' + rpi_exporter_version + '/sha256sums.txt', wantlist=True) | list }}"
  run_once: true

- name: "Get checksum for {{ go_arch }} architecture"
  set_fact:
    rpi_exporter_checksum: "{{ item.split(' ')[0] }}"
  with_items: "{{ _checksums }}"
  when: "('linux-' + go_arch + '.tar.gz') in item"
